yolo_model:

  config_file:
    name: yolov3_project.cfg
  weight_file:
    name: yolov3_project_20000.weights
  threshold:
    value: 0.3
  detection_classes:
    names: 
      - child
      - limit_speed
      - lottery
      - park
      - people
      - tunnel
      - turn_limit
      - turtle
      - unlimit